# Generated by Django 4.1.6 on 2023-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
