# Generated by Django 4.1.6 on 2023-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingen', '0002_transacao_recorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='meses',
            field=models.IntegerField(default=1),
        ),
    ]
